# Generated by Django 4.2.20 on 2025-03-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='time',
            field=models.DateField(),
        ),
    ]
