# Generated by Django 4.2.20 on 2025-03-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_educationmodel_time_alter_experiencemodel_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationModel',
            new_name='Education',
        ),
        migrations.RenameModel(
            old_name='ExperienceModel',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='PositionPersonModel',
            new_name='PositionPerson',
        ),
    ]
