# Generated by Django 4.2.20 on 2025-03-19 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_rename_educationmodel_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='time_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='time_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
