# Generated by Django 4.2.20 on 2025-03-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_education_time_end_experience_time_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
