# Generated by Django 4.2.20 on 2025-03-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
