# Generated by Django 4.2.20 on 2025-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_project_url_alter_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='position',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='work',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
