# Generated by Django 4.2.20 on 2025-03-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_rename_position_image_title_remove_image_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default='images/icons/icon-close.svg', upload_to='uploads/'),
        ),
    ]
