# Generated by Django 4.2.20 on 2025-03-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
