# Generated by Django 4.2.20 on 2025-03-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_remove_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='personal.ip'),
        ),
    ]
